name: Update Config

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      nextRideDate:
        description: 'Next Ride Date'
        required: true
        default: ''
      nextRideTime:
        description: 'Next Ride Time'
        required: true
        default: ''
      nextRideLocation:
        description: 'Next Ride Location'
        required: true
        default: ''
      nextRideStravaRouteUrl:
        description: 'Next Ride Strava Route URL'
        required: true
        default: ''
      nextRideInfo:
        description: 'Next Ride Info'
        required: true
        default: ''

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update next.config.js
        run: |
          sed -i 's|nextRideDate: .*|nextRideDate: '\''${{ github.event.inputs.nextRideDate }}'\'',|' next.config.js
          sed -i 's|nextRideTime: .*|nextRideTime: '\''${{ github.event.inputs.nextRideTime }}'\'',|' next.config.js
          sed -i 's|nextRideLocation: .*|nextRideLocation: '\''${{ github.event.inputs.nextRideLocation }}'\'',|' next.config.js
          sed -i 's|nextRideStravaRouteUrl: .*|nextRideStravaRouteUrl: '\''${{ github.event.inputs.nextRideStravaRouteUrl }}'\'',|' next.config.js
          sed -i 's|nextRideInfo: .*|nextRideInfo: '\''${{ github.event.inputs.nextRideInfo }}'\'',|' next.config.js

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add next.config.js
          git commit -m 'Update next ride details'

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
